/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab12;

import java.io.IOError;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {

        try {

            File file = new File("/Users/sonia/Desktop/Files/tinyG.txt");
            // File file = new File("/Users/sonia/Desktop/Files/top_DG2.txt");
            //File file = new File("/Users/sonia/Desktop/Files/mediumG.txt");
            Scanner scanner = new Scanner(file);

            int num_vertices = scanner.nextInt();
            int edges = scanner.nextInt();
            System.out.println("Number of vertices: " + num_vertices);
            Graph graph = new Graph(num_vertices);

            while (scanner.hasNextInt()) {
                int u = scanner.nextInt();
                int v = scanner.nextInt();
                graph.edge_addition(u, v);
            }
            scanner.close();


            graph.printGraph();
            graph.DFS(num_vertices);
            graph.topologicalSort();
        } catch (FileNotFoundException e) {
            System.out.println("File not found!");
        }
    }
}
